export const FETCH_SLIDER_DATA_START =  'FETCH_SLIDER_DATA_START';
export const FETCH_SLIDER_DATA_SUCCESS = 'FETCH_SLIDER_DATA_SUCCESS';
export const FETCH_SLIDER_DATA_FAIL = 'FETCH_SLIDER_DATA_FAIL';


export const NEXT_SLIDER ='NEXT_SLIDER';
export const PREVIOUS_SLIDER ='PREVIOUS_SLIDER';


export const CATEGORY_START ='CATEGORY_START';
export const CATEGORY_SUCCESS ='CATEGORY_SUCCESS';
export const CATEGORY_FAIL ='CATEGORY_FAIL';

export const PROPERTY_START= 'PROPERTY_START';
export const PROPERTY_SUCCESS= 'PROPERTY_SUCCESS';
export const PROPERTY_FAIL = 'PROPERTY_FAIL';
export const FILTERED_DATA = 'FILTERED_DATA';